# Generated by Django 4.1.7 on 2023-02-15 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mouvements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=255)),
                ('camions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='tracker.camions')),
            ],
        ),
        migrations.CreateModel(
            name='MouvementDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure', models.TimeField(auto_now=True)),
                ('mouvements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_details', to='tracker.mouvements')),
                ('steps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_details', to='tracker.steps')),
            ],
        ),
    ]
