# Generated by Django 4.1.7 on 2023-02-15 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementdetails',
            name='mouvements',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mouvements_details', to='tracker.mouvements'),
        ),
        migrations.AlterField(
            model_name='mouvementdetails',
            name='steps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mouvements_details', to='tracker.steps'),
        ),
        migrations.AlterField(
            model_name='mouvements',
            name='camions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mouvements', to='tracker.camions'),
        ),
        migrations.AlterField(
            model_name='mouvements',
            name='status',
            field=models.CharField(choices=[('En attente', '1'), ('En cours', '2'), ('Annulé', '3'), ('Cloturé', '4')], default='1', max_length=255),
        ),
    ]
