# Generated by Django 4.1.7 on 2023-02-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_steps_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='steps',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
