# Generated by Django 4.1.7 on 2023-02-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_steps_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='checkpoint',
            field=models.CharField(max_length=255),
        ),
    ]
