# Generated by Django 4.1.7 on 2023-02-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_steps_checkpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mouvementdetails',
            name='steps',
        ),
        migrations.AddField(
            model_name='mouvementdetails',
            name='status',
            field=models.CharField(choices=[('En cours', '1'), ('Terminé', '2')], default='1', max_length=255),
        ),
    ]
