# Generated by Django 4.1.7 on 2023-02-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_remove_mouvementdetails_steps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementdetails',
            name='step',
            field=models.IntegerField(default=0),
        ),
    ]
