# Generated by Django 4.1.7 on 2023-02-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_mouvementdetails_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='camions',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chauffeur',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mouvements',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mouvements',
            name='remote_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
