# Generated by Django 4.1.7 on 2023-02-17 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_camions_is_active_chauffeur_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvements',
            name='chauffeurs',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='tracker.chauffeur'),
            preserve_default=False,
        ),
    ]
