# Generated by Django 4.1.7 on 2023-02-17 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_mouvements_chauffeurs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mouvements',
            name='camions',
        ),
        migrations.AddField(
            model_name='mouvements',
            name='camion',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='tracker.camions'),
            preserve_default=False,
        ),
    ]
