# Generated by Django 4.1.7 on 2023-02-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_alter_mouvementdetails_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementdetails',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
