# Generated by Django 4.1.7 on 2023-02-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_mouvementdetails_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementdetails',
            name='checkpoint',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mouvementdetails',
            name='step',
            field=models.IntegerField(default=0),
        ),
    ]
