# Generated by Django 4.1.7 on 2023-02-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_mouvementdetails_checkpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouvementdetails',
            name='date_op',
            field=models.DateTimeField(null=True),
        ),
    ]
