# Generated by Django 4.1.7 on 2023-02-22 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_steps_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='camions',
            name='steps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tracker.steps'),
        ),
    ]
