# Generated by Django 4.1.7 on 2023-02-22 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_camions_steps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camions',
            name='steps',
        ),
    ]
